{"links": {"self": {"href": "data/repositories/osrf/sdformat/issues/151/comments/47568091.json"}, "html": {"href": "#!/osrf/sdformat/issues/151#comment-47568091"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/sdformat/issues/151.json"}}, "type": "issue", "id": 151, "repository": {"links": {"self": {"href": "data/repositories/osrf/sdformat.json"}, "html": {"href": "#!/osrf/sdformat"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b6d52f9f-b070-41c0-807c-94af07ea375b}ts=1606789"}}, "type": "repository", "name": "sdformat", "full_name": "osrf/sdformat", "uuid": "{b6d52f9f-b070-41c0-807c-94af07ea375b}"}, "title": "Trying to parse an invalid file gives URDF parser error"}, "content": {"raw": "Currently running into this problem. Not sure what's wrong with my SDF yet(`gz sdf -k file.sdf` returns `Check Complete`), but the errors I see made me believe it's parsing an URDF.", "markup": "markdown", "html": "<p>Currently running into this problem. Not sure what's wrong with my SDF yet(<code>gz sdf -k file.sdf</code> returns <code>Check Complete</code>), but the errors I see made me believe it's parsing an URDF.</p>", "type": "rendered"}, "created_on": "2018-09-01T13:18:39.535999+00:00", "user": {"display_name": "Jordan Lack", "uuid": "{a47ca146-169c-4fcf-b59f-8410d9f676ff}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba47ca146-169c-4fcf-b59f-8410d9f676ff%7D"}, "html": {"href": "https://bitbucket.org/%7Ba47ca146-169c-4fcf-b59f-8410d9f676ff%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:82c7a832-85b7-45f4-86fc-e63688f35a2d/e5a6704f-a784-4c66-94ff-f7a9c914403a/128"}}, "nickname": "jordanlack", "type": "user", "account_id": "557058:82c7a832-85b7-45f4-86fc-e63688f35a2d"}, "updated_on": null, "type": "issue_comment", "id": 47568091}