{"rendered": {"description": {"raw": "I noticed that it wasn't possible to run test coverage for SDF. Running this:\r\n\r\n`cmake .. -DCMAKE_BUILD_TYPE=coverage`\r\n\r\nWould give this error:\r\n\r\n~~~\r\nCMake Error at CMakeLists.txt:132 (include):\r\n  include could not find load file:\r\n\r\n    /home/louise/code/sdformat/cmake/CodeCoverage.cmake\r\n~~~\r\n\r\nSo I copied `CodeCoverage.cmake` from ignition math here, and was able to build coverage.\r\n\r\n### Coverage\r\n\r\n1. Install lcov: `sudo apt-get install lcov`\r\n\r\n1. `cmake -DCMAKE_BUILD_TYPE=coverage ../; make`\r\n\r\n1. run tests (`make test`, or individual tests)\r\n\r\n1. `make coverage`\r\n\r\n1. `firefox coverage/index.html`\r\n\r\nYou'll see a really red report like this:\r\n\r\n![lcovsdf.png](data/bitbucket.org/repo/ak8x4z/images/3595241416-lcovsdf.png)\r\n\r\n\r\n### Exception copy constructor to fix test segfault\r\n\r\nFor some reason, `UNIT_Exception_TEST` fails with a segfault on `~Exception` when trying to `delete this->dataPtr`, but only when running test coverage, so it is [not failing on Jenkins](http://build.osrfoundation.org/view/main/view/BuildCopFail/job/sdformat-ci-sdformat4-xenial-amd64/6/consoleFull).\r\n\r\nAfter some investigation I noticed there were two calls to the destructor. [This](http://stackoverflow.com/questions/30309038/why-is-the-destructor-of-an-exception-called-twice) gave the idea of adding a copy constructor, and it turns out that fixed the problem for me.", "markup": "markdown", "html": "<p>I noticed that it wasn't possible to run test coverage for SDF. Running this:</p>\n<p><code>cmake .. -DCMAKE_BUILD_TYPE=coverage</code></p>\n<p>Would give this error:</p>\n<div class=\"codehilite\"><pre><span></span>CMake Error at CMakeLists.txt:132 (include):\n  include could not find load file:\n\n    /home/louise/code/sdformat/cmake/CodeCoverage.cmake\n</pre></div>\n\n\n<p>So I copied <code>CodeCoverage.cmake</code> from ignition math here, and was able to build coverage.</p>\n<h3 id=\"markdown-header-coverage\">Coverage</h3>\n<ol>\n<li>\n<p>Install lcov: <code>sudo apt-get install lcov</code></p>\n</li>\n<li>\n<p><code>cmake -DCMAKE_BUILD_TYPE=coverage ../; make</code></p>\n</li>\n<li>\n<p>run tests (<code>make test</code>, or individual tests)</p>\n</li>\n<li>\n<p><code>make coverage</code></p>\n</li>\n<li>\n<p><code>firefox coverage/index.html</code></p>\n</li>\n</ol>\n<p>You'll see a really red report like this:</p>\n<p><img alt=\"lcovsdf.png\" src=\"data/bitbucket.org/repo/ak8x4z/images/3595241416-lcovsdf.png\" /></p>\n<h3 id=\"markdown-header-exception-copy-constructor-to-fix-test-segfault\">Exception copy constructor to fix test segfault</h3>\n<p>For some reason, <code>UNIT_Exception_TEST</code> fails with a segfault on <code>~Exception</code> when trying to <code>delete this-&gt;dataPtr</code>, but only when running test coverage, so it is <a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/view/main/view/BuildCopFail/job/sdformat-ci-sdformat4-xenial-amd64/6/consoleFull\" rel=\"nofollow\">not failing on Jenkins</a>.</p>\n<p>After some investigation I noticed there were two calls to the destructor. <a data-is-external-link=\"true\" href=\"http://stackoverflow.com/questions/30309038/why-is-the-destructor-of-an-exception-called-twice\" rel=\"nofollow\">This</a> gave the idea of adding a copy constructor, and it turns out that fixed the problem for me.</p>", "type": "rendered"}, "title": {"raw": "Test coverage", "markup": "markdown", "html": "<p>Test coverage</p>", "type": "rendered"}}, "type": "pullrequest", "description": "I noticed that it wasn't possible to run test coverage for SDF. Running this:\r\n\r\n`cmake .. -DCMAKE_BUILD_TYPE=coverage`\r\n\r\nWould give this error:\r\n\r\n~~~\r\nCMake Error at CMakeLists.txt:132 (include):\r\n  include could not find load file:\r\n\r\n    /home/louise/code/sdformat/cmake/CodeCoverage.cmake\r\n~~~\r\n\r\nSo I copied `CodeCoverage.cmake` from ignition math here, and was able to build coverage.\r\n\r\n### Coverage\r\n\r\n1. Install lcov: `sudo apt-get install lcov`\r\n\r\n1. `cmake -DCMAKE_BUILD_TYPE=coverage ../; make`\r\n\r\n1. run tests (`make test`, or individual tests)\r\n\r\n1. `make coverage`\r\n\r\n1. `firefox coverage/index.html`\r\n\r\nYou'll see a really red report like this:\r\n\r\n![lcovsdf.png](data/bitbucket.org/repo/ak8x4z/images/3595241416-lcovsdf.png)\r\n\r\n\r\n### Exception copy constructor to fix test segfault\r\n\r\nFor some reason, `UNIT_Exception_TEST` fails with a segfault on `~Exception` when trying to `delete this->dataPtr`, but only when running test coverage, so it is [not failing on Jenkins](http://build.osrfoundation.org/view/main/view/BuildCopFail/job/sdformat-ci-sdformat4-xenial-amd64/6/consoleFull).\r\n\r\nAfter some investigation I noticed there were two calls to the destructor. [This](http://stackoverflow.com/questions/30309038/why-is-the-destructor-of-an-exception-called-twice) gave the idea of adding a copy constructor, and it turns out that fixed the problem for me.", "links": {"decline": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/pullrequests/317/decline"}, "diffstat": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/diffstat/osrf/sdformat:bf25471c6438%0D5c710e08d69c?from_pullrequest_id=317"}, "commits": {"href": "data/repositories/osrf/sdformat/pullrequests/317/commits.json"}, "self": {"href": "data/repositories/osrf/sdformat/pullrequests/317.json"}, "comments": {"href": "data/repositories/osrf/sdformat/pullrequests/317/comments_page=1.json"}, "merge": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/pullrequests/317/merge"}, "html": {"href": "#!/osrf/sdformat/pull-requests/317"}, "activity": {"href": "data/repositories/osrf/sdformat/pullrequests/317/activity.json"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/diff/osrf/sdformat:bf25471c6438%0D5c710e08d69c?from_pullrequest_id=317"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/pullrequests/317/approve"}, "statuses": {"href": "data/repositories/osrf/sdformat/pullrequests/317/statuses_page=1.json"}}, "title": "Test coverage", "close_source_branch": true, "reviewers": [], "id": 317, "destination": {"commit": {"hash": "5c710e08d69c", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/sdformat/commit/5c710e08d69c.json"}, "html": {"href": "#!/osrf/sdformat/commits/5c710e08d69c"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/sdformat.json"}, "html": {"href": "#!/osrf/sdformat"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b6d52f9f-b070-41c0-807c-94af07ea375b}ts=1606789"}}, "type": "repository", "name": "sdformat", "full_name": "osrf/sdformat", "uuid": "{b6d52f9f-b070-41c0-807c-94af07ea375b}"}, "branch": {"name": "sdf4"}}, "created_on": "2017-02-17T17:21:51.424902+00:00", "summary": {"raw": "I noticed that it wasn't possible to run test coverage for SDF. Running this:\r\n\r\n`cmake .. -DCMAKE_BUILD_TYPE=coverage`\r\n\r\nWould give this error:\r\n\r\n~~~\r\nCMake Error at CMakeLists.txt:132 (include):\r\n  include could not find load file:\r\n\r\n    /home/louise/code/sdformat/cmake/CodeCoverage.cmake\r\n~~~\r\n\r\nSo I copied `CodeCoverage.cmake` from ignition math here, and was able to build coverage.\r\n\r\n### Coverage\r\n\r\n1. Install lcov: `sudo apt-get install lcov`\r\n\r\n1. `cmake -DCMAKE_BUILD_TYPE=coverage ../; make`\r\n\r\n1. run tests (`make test`, or individual tests)\r\n\r\n1. `make coverage`\r\n\r\n1. `firefox coverage/index.html`\r\n\r\nYou'll see a really red report like this:\r\n\r\n![lcovsdf.png](data/bitbucket.org/repo/ak8x4z/images/3595241416-lcovsdf.png)\r\n\r\n\r\n### Exception copy constructor to fix test segfault\r\n\r\nFor some reason, `UNIT_Exception_TEST` fails with a segfault on `~Exception` when trying to `delete this->dataPtr`, but only when running test coverage, so it is [not failing on Jenkins](http://build.osrfoundation.org/view/main/view/BuildCopFail/job/sdformat-ci-sdformat4-xenial-amd64/6/consoleFull).\r\n\r\nAfter some investigation I noticed there were two calls to the destructor. [This](http://stackoverflow.com/questions/30309038/why-is-the-destructor-of-an-exception-called-twice) gave the idea of adding a copy constructor, and it turns out that fixed the problem for me.", "markup": "markdown", "html": "<p>I noticed that it wasn't possible to run test coverage for SDF. Running this:</p>\n<p><code>cmake .. -DCMAKE_BUILD_TYPE=coverage</code></p>\n<p>Would give this error:</p>\n<div class=\"codehilite\"><pre><span></span>CMake Error at CMakeLists.txt:132 (include):\n  include could not find load file:\n\n    /home/louise/code/sdformat/cmake/CodeCoverage.cmake\n</pre></div>\n\n\n<p>So I copied <code>CodeCoverage.cmake</code> from ignition math here, and was able to build coverage.</p>\n<h3 id=\"markdown-header-coverage\">Coverage</h3>\n<ol>\n<li>\n<p>Install lcov: <code>sudo apt-get install lcov</code></p>\n</li>\n<li>\n<p><code>cmake -DCMAKE_BUILD_TYPE=coverage ../; make</code></p>\n</li>\n<li>\n<p>run tests (<code>make test</code>, or individual tests)</p>\n</li>\n<li>\n<p><code>make coverage</code></p>\n</li>\n<li>\n<p><code>firefox coverage/index.html</code></p>\n</li>\n</ol>\n<p>You'll see a really red report like this:</p>\n<p><img alt=\"lcovsdf.png\" src=\"data/bitbucket.org/repo/ak8x4z/images/3595241416-lcovsdf.png\" /></p>\n<h3 id=\"markdown-header-exception-copy-constructor-to-fix-test-segfault\">Exception copy constructor to fix test segfault</h3>\n<p>For some reason, <code>UNIT_Exception_TEST</code> fails with a segfault on <code>~Exception</code> when trying to <code>delete this-&gt;dataPtr</code>, but only when running test coverage, so it is <a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/view/main/view/BuildCopFail/job/sdformat-ci-sdformat4-xenial-amd64/6/consoleFull\" rel=\"nofollow\">not failing on Jenkins</a>.</p>\n<p>After some investigation I noticed there were two calls to the destructor. <a data-is-external-link=\"true\" href=\"http://stackoverflow.com/questions/30309038/why-is-the-destructor-of-an-exception-called-twice\" rel=\"nofollow\">This</a> gave the idea of adding a copy constructor, and it turns out that fixed the problem for me.</p>", "type": "rendered"}, "source": {"commit": {"hash": "13ae792556ea", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/sdformat/commit/13ae792556ea.json"}, "html": {"href": "#!/osrf/sdformat/commits/13ae792556ea"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/sdformat.json"}, "html": {"href": "#!/osrf/sdformat"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b6d52f9f-b070-41c0-807c-94af07ea375b}ts=1606789"}}, "type": "repository", "name": "sdformat", "full_name": "osrf/sdformat", "uuid": "{b6d52f9f-b070-41c0-807c-94af07ea375b}"}, "branch": {"name": "exception_copy_4"}}, "comment_count": 8, "state": "MERGED", "task_count": 0, "participants": [{"role": "PARTICIPANT", "participated_on": "2017-02-17T19:26:50.246041+00:00", "type": "participant", "approved": true, "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}}, {"role": "PARTICIPANT", "participated_on": "2017-02-22T00:23:01.218914+00:00", "type": "participant", "approved": true, "user": {"display_name": "clalancette", "uuid": "{02b311e1-297d-4232-89c4-5485d0a02911}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B02b311e1-297d-4232-89c4-5485d0a02911%7D"}, "html": {"href": "https://bitbucket.org/%7B02b311e1-297d-4232-89c4-5485d0a02911%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:ad6ed80b-ec66-45cb-9504-b1094a415b7f/048a0933-60ac-4910-a6a5-ed058bdea8eb/128"}}, "nickname": "clalancette", "type": "user", "account_id": "557058:ad6ed80b-ec66-45cb-9504-b1094a415b7f"}}, {"role": "PARTICIPANT", "participated_on": "2017-02-22T15:39:02.668823+00:00", "type": "participant", "approved": false, "user": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}}], "reason": "", "updated_on": "2017-02-22T18:08:15.957646+00:00", "author": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}, "merge_commit": {"hash": "bf25471c6438", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/sdformat/commit/bf25471c6438.json"}, "html": {"href": "#!/osrf/sdformat/commits/bf25471c6438"}}}, "closed_by": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}}