{"links": {"self": {"href": "data/repositories/osrf/sdformat/issues/165/comments/39045915.json"}, "html": {"href": "#!/osrf/sdformat/issues/165#comment-39045915"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/sdformat/issues/165.json"}}, "type": "issue", "id": 165, "repository": {"links": {"self": {"href": "data/repositories/osrf/sdformat.json"}, "html": {"href": "#!/osrf/sdformat"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b6d52f9f-b070-41c0-807c-94af07ea375b}ts=1606789"}}, "type": "repository", "name": "sdformat", "full_name": "osrf/sdformat", "uuid": "{b6d52f9f-b070-41c0-807c-94af07ea375b}"}, "title": "Issue when attempting to scale model"}, "content": {"raw": "This is probably true and has not worked before. If I recall correctly, we added `<scale>` to model to support scaling through the UI client but we don't actually read that sdf value when spawning models in the  world.\n\nAs a workaround, you'll need to specify the exact size of your geometry (or scale if it's a mesh geom) in your collision and visual element.", "markup": "markdown", "html": "<p>This is probably true and has not worked before. If I recall correctly, we added <code>&lt;scale&gt;</code> to model to support scaling through the UI client but we don't actually read that sdf value when spawning models in the  world.</p>\n<p>As a workaround, you'll need to specify the exact size of your geometry (or scale if it's a mesh geom) in your collision and visual element.</p>", "type": "rendered"}, "created_on": "2017-08-12T00:44:17.721408+00:00", "user": {"display_name": "Ian Chen", "uuid": "{eaa6fca5-6deb-43f6-907f-971c144735dd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D"}, "html": {"href": "https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5/1e4adcdf-1946-4280-9aea-eb5f15a7f912/128"}}, "nickname": "Ian Chen", "type": "user", "account_id": "557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5"}, "updated_on": null, "type": "issue_comment", "id": 39045915}